version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Entered build phase..
      - mvn clean install
  post_build:
    commands:
      - echo build completed successfully
artifacts:
  files:
    - target/pms-ui-service.jar
  discard-paths: yes